name: Cypress Tests

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 9 * * *' # Executa todos os dias Ã s 09h UTC

jobs:
  cypress:
    runs-on: windows-latest

    steps:
      - name: ğŸ”„ Check out repository
        uses: actions/checkout@v3

      - name: âš™ï¸ Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: ğŸ“¦ Install dependencies
        run: npm ci

      - name: ğŸ§ª Run Cypress tests on Firefox
        uses: cypress-io/github-action@v5
        with:
          browser: firefox

      - name: ğŸ› ï¸ Install Allure CLI
        run: npm install -g allure-commandline --save-exact

      - name: ğŸ“Š Generate Allure Report
        if: always()
        run: npm run report:allure

      - name: ğŸ“ Upload Cypress artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Cypress-Artifacts
          path: |
            allure-results/
            allure-report/
            cypress/videos/
            cypress/screenshots/

      - name: ğŸ”” Send Slack notification on failure
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          if [ -z "${GITHUB_RUN_URL}" ]; then
            GITHUB_RUN_URL="https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
          fi
          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"âš ï¸ O job *Cypress Tests* falhou no commit: <${GITHUB_SHA}|${GITHUB_SHA}> no projeto: ${GITHUB_REPOSITORY}. Verifique os relatÃ³rios de teste em: <${GITHUB_RUN_URL}|Clique aqui para ver os detalhes>\", \"icon_url\": \"https://example.com/automation-icon.png\"}" \
          $SLACK_WEBHOOK_URL
